"""
Test Suite: Redis Cache Integration (Fix 4)
============================================

Tests:
    1. Cache miss → agentic workflow executes
    2. Cache hit → cached response returned without workflow
    3. Cache storage → final answer stored in Redis
    4. Cache key consistency → same query always yields same key
    5. Redis unavailable → application continues gracefully
    6. Cache Hit Rate → dynamically calculated from actual hit/miss counts
"""

import hashlib
from unittest.mock import MagicMock, patch

import pytest

pytestmark = pytest.mark.unit

import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from app.utils.redis_cache import (
    CACHE_KEY_PREFIX,
    cache_get,
    cache_set,
    generate_cache_key,
    get_cache_hit_rate,
    normalize_query,
    reset_cache_counters,
    reset_redis_client,
)

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _make_fake_redis(stored: dict = None):
    """Create a mock Redis client backed by an in-memory dict."""
    store = stored or {}
    mock = MagicMock()

    def _get(key):
        return store.get(key)

    def _setex(key, ttl, value):
        store[key] = value
        return True

    def _delete(key):
        store.pop(key, None)
        return 1

    mock.ping.return_value = True
    mock.get.side_effect = _get
    mock.setex.side_effect = _setex
    mock.delete.side_effect = _delete
    return mock, store


# ---------------------------------------------------------------------------
# Test 1 — Cache Miss → agentic workflow runs
# ---------------------------------------------------------------------------

def test_cache_miss_returns_none():
    """
    Test 1: When Redis has no entry for the query, cache_get returns None.
    This triggers the agentic workflow to run.
    """
    reset_cache_counters()
    reset_redis_client()

    fake_redis, _ = _make_fake_redis(stored={})

    with patch("app.utils.redis_cache._get_redis_client", return_value=fake_redis):
        result = cache_get("latest AI news today")

    assert result is None, f"Expected None for cache miss, got: {result}"


def test_cache_miss_increments_miss_counter():
    """
    Test 1b: A cache miss correctly increments the miss counter.
    """
    reset_cache_counters()
    reset_redis_client()

    fake_redis, _ = _make_fake_redis(stored={})

    with patch("app.utils.redis_cache._get_redis_client", return_value=fake_redis):
        cache_get("some new query")
        rate = get_cache_hit_rate()

    # 0 hits, 1 miss → rate = 0.0
    assert rate == 0.0, f"Expected 0.0 hit rate after miss, got {rate}"


# ---------------------------------------------------------------------------
# Test 2 — Cache Hit → cached response returned
# ---------------------------------------------------------------------------

def test_cache_hit_returns_stored_response():
    """
    Test 2: When Redis has a valid entry, cache_get returns it.
    The agentic workflow should NOT run (handled by should_use_cache in workflow).
    """
    reset_cache_counters()
    reset_redis_client()

    query = "Compare BBC and NDTV coverage of AI"
    expected_response = "## Intelligence Briefing: BBC vs NDTV..."
    key = generate_cache_key(query)

    fake_redis, store = _make_fake_redis(stored={key: expected_response})

    with patch("app.utils.redis_cache._get_redis_client", return_value=fake_redis):
        result = cache_get(query)

    assert result == expected_response, \
        f"Expected cached response, got: {result}"


def test_cache_hit_increments_hit_counter():
    """
    Test 2b: A cache hit correctly increments the hit counter.
    """
    reset_cache_counters()
    reset_redis_client()

    query = "Find the latest AI news"
    key = generate_cache_key(query)
    fake_redis, _ = _make_fake_redis(stored={key: "Cached AI news response"})

    with patch("app.utils.redis_cache._get_redis_client", return_value=fake_redis):
        cache_get(query)
        rate = get_cache_hit_rate()

    # 1 hit, 0 misses → rate = 1.0
    assert rate == 1.0, f"Expected 1.0 hit rate after hit, got {rate}"


# ---------------------------------------------------------------------------
# Test 3 — Cache Storage → final answer stored in Redis
# ---------------------------------------------------------------------------

def test_cache_set_stores_response():
    """
    Test 3: cache_set stores the response in Redis under the correct key.
    Verifies that the final answer generated by the agentic workflow is persisted.
    """
    reset_redis_client()

    query = "What are the trending topics this week?"
    response = "## Top Trending Topics: AI, Elections, Economy..."
    key = generate_cache_key(query)

    fake_redis, store = _make_fake_redis()

    with patch("app.utils.redis_cache._get_redis_client", return_value=fake_redis):
        success = cache_set(query, response)

    assert success is True, "cache_set should return True on success"
    assert store.get(key) == response, \
        f"Expected stored response '{response}', got '{store.get(key)}'"


def test_cache_set_uses_correct_ttl():
    """
    Test 3b: cache_set calls Redis setex with the configured TTL.
    """
    reset_redis_client()

    query = "Show the current news analytics"
    response = "Dashboard analytics response"
    fake_redis, _ = _make_fake_redis()

    with patch("app.utils.redis_cache._get_redis_client", return_value=fake_redis):
        cache_set(query, response, ttl=300)

    # Verify setex was called with TTL=300
    key = generate_cache_key(query)
    fake_redis.setex.assert_called_once_with(key, 300, response)


# ---------------------------------------------------------------------------
# Test 4 — Cache Key Consistency
# ---------------------------------------------------------------------------

def test_cache_key_deterministic_same_query():
    """
    Test 4: The same query always produces the exact same cache key.
    No random values, no timestamps — purely deterministic SHA-256.
    """
    query = "Find the latest AI news"
    key1 = generate_cache_key(query)
    key2 = generate_cache_key(query)
    key3 = generate_cache_key(query)

    assert key1 == key2 == key3, \
        "Same query must always produce the same cache key"
    assert key1.startswith(CACHE_KEY_PREFIX), \
        f"Cache key must start with '{CACHE_KEY_PREFIX}'"


def test_cache_key_normalization_consistency():
    """
    Test 4b: Queries that differ only in case/whitespace/punctuation
    produce the SAME cache key after normalization.
    """
    q1 = "Find the latest AI news"
    q2 = "find the latest ai news"
    q3 = "  Find  The  Latest  AI  News  "

    key1 = generate_cache_key(q1)
    key2 = generate_cache_key(q2)
    key3 = generate_cache_key(q3)

    assert key1 == key2 == key3, \
        "Case/whitespace variations must produce the same cache key"


def test_cache_key_different_queries_produce_different_keys():
    """
    Test 4c: Different queries must produce different cache keys.
    """
    key_ai = generate_cache_key("Find the latest AI news")
    key_cricket = generate_cache_key("India wins cricket match")

    assert key_ai != key_cricket, \
        "Different queries must produce different cache keys"


def test_cache_key_contains_sha256_digest():
    """
    Test 4d: The cache key ends with a valid SHA-256 hex digest.
    """
    query = "Show the current news analytics"
    normalized = normalize_query(query)
    expected_digest = hashlib.sha256(normalized.encode("utf-8")).hexdigest()
    expected_key = f"{CACHE_KEY_PREFIX}{expected_digest}"

    actual_key = generate_cache_key(query)
    assert actual_key == expected_key, \
        f"Expected key '{expected_key}', got '{actual_key}'"


# ---------------------------------------------------------------------------
# Test 5 — Redis Unavailable → graceful degradation
# ---------------------------------------------------------------------------

def test_cache_get_returns_none_when_redis_unavailable():
    """
    Test 5a: When Redis is unavailable, cache_get returns None gracefully.
    The application should NOT crash.
    """
    reset_cache_counters()
    reset_redis_client()

    with patch("app.utils.redis_cache._get_redis_client", return_value=None):
        result = cache_get("some query")

    assert result is None, \
        "cache_get must return None gracefully when Redis is unavailable"


def test_cache_set_returns_false_when_redis_unavailable():
    """
    Test 5b: When Redis is unavailable, cache_set returns False gracefully.
    The application should NOT crash.
    """
    reset_redis_client()

    with patch("app.utils.redis_cache._get_redis_client", return_value=None):
        result = cache_set("some query", "some response")

    assert result is False, \
        "cache_set must return False gracefully when Redis is unavailable"


def test_workflow_continues_when_redis_raises_exception():
    """
    Test 5c: When Redis raises an exception mid-operation, cache_get handles it
    gracefully and returns None without crashing the application.
    """
    reset_cache_counters()
    reset_redis_client()

    broken_redis = MagicMock()
    broken_redis.get.side_effect = ConnectionError("Redis connection lost")

    with patch("app.utils.redis_cache._get_redis_client", return_value=broken_redis):
        result = cache_get("any query")

    assert result is None, \
        "cache_get must handle Redis exceptions gracefully and return None"


# ---------------------------------------------------------------------------
# Test 6 — Cache Hit Rate dynamically calculated
# ---------------------------------------------------------------------------

def test_cache_hit_rate_dynamic_calculation():
    """
    Test 6: Cache Hit Rate = hits / (hits + misses), calculated dynamically.
    Verifies: 2 hits + 1 miss = 66.67% hit rate.
    """
    reset_cache_counters()
    reset_redis_client()

    query = "Compare BBC and NDTV coverage"
    key = generate_cache_key(query)

    # 2 hits
    fake_redis, _ = _make_fake_redis(stored={key: "Cached response"})
    with patch("app.utils.redis_cache._get_redis_client", return_value=fake_redis):
        cache_get(query)   # HIT
        cache_get(query)   # HIT

    # 1 miss
    fake_redis2, _ = _make_fake_redis(stored={})
    with patch("app.utils.redis_cache._get_redis_client", return_value=fake_redis2):
        cache_get("completely different query that is not cached")  # MISS

    rate = get_cache_hit_rate()
    assert 0.60 <= rate <= 0.70, \
        f"Expected ~0.667 hit rate (2 hits, 1 miss), got {rate}"


def test_cache_hit_rate_zero_when_no_requests():
    """
    Test 6b: Hit rate is 0.0 when no cache operations have occurred.
    """
    reset_cache_counters()
    rate = get_cache_hit_rate()
    assert rate == 0.0, f"Expected 0.0 hit rate with no requests, got {rate}"


def test_cache_hit_rate_changes_with_more_hits():
    """
    Test 6c: Hit rate increases dynamically as more hits occur.
    """
    reset_cache_counters()
    reset_redis_client()

    query = "Find AI news"
    key = generate_cache_key(query)

    # First: 1 miss
    fake_miss = _make_fake_redis(stored={})[0]
    with patch("app.utils.redis_cache._get_redis_client", return_value=fake_miss):
        cache_get("not cached")

    rate_after_miss = get_cache_hit_rate()
    assert rate_after_miss == 0.0

    # Then: 1 hit
    fake_hit = _make_fake_redis(stored={key: "Response"})[0]
    with patch("app.utils.redis_cache._get_redis_client", return_value=fake_hit):
        cache_get(query)

    rate_after_hit = get_cache_hit_rate()
    assert rate_after_hit > rate_after_miss, \
        "Hit rate must increase after a cache hit"
    assert rate_after_hit == 0.5, \
        f"Expected 0.5 (1 hit, 1 miss), got {rate_after_hit}"
